test-log -> test-trace

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -13,29 +13,29 @@ jobs:
     outputs:
       version: ${{ steps.version.outputs.version }}
     steps:
-    - uses: actions/checkout@v4
-    - id: version
-      shell: bash
-      run: |
-        cargo generate-lockfile
-        pkgid="$(cargo pkgid)"
-        # Format is typically
-        #   file://<path>/<crate>#<version>
-        # but could also be along the lines of
-        #   file://<path>/<crate>#<actual-crate-name>@<version>
-        version="$(echo ${pkgid}                   | cut -d '#' -f2 | cut -d '@' -f2 | grep -o '[^:]*$')"
-        macros_version="$(cd macros && cargo pkgid | cut -d '#' -f2 | cut -d '@' -f2 | grep -o '[^:]*$')"
+      - uses: actions/checkout@v4
+      - id: version
+        shell: bash
+        run: |
+          cargo generate-lockfile
+          pkgid="$(cargo pkgid)"
+          # Format is typically
+          #   file://<path>/<crate>#<version>
+          # but could also be along the lines of
+          #   file://<path>/<crate>#<actual-crate-name>@<version>
+          version="$(echo ${pkgid}                   | cut -d '#' -f2 | cut -d '@' -f2 | grep -o '[^:]*$')"
+          macros_version="$(cd macros && cargo pkgid | cut -d '#' -f2 | cut -d '@' -f2 | grep -o '[^:]*$')"
 
-        if [ -z "${version}" ]; then
-          echo "Invalid version string: ${pkgid}"
-          exit 1
-        fi
-        if [ "${version}" != "${macros_version}" ]; then
-          echo "test-log and test-log-macros have differing version (${version} vs. ${macros_version}"
-          exit 1
-        fi
-        echo "Determined crate version: ${version}"
-        echo "version=${version}" >> $GITHUB_OUTPUT
+          if [ -z "${version}" ]; then
+            echo "Invalid version string: ${pkgid}"
+            exit 1
+          fi
+          if [ "${version}" != "${macros_version}" ]; then
+            echo "test-trace and test-trace-macros have differing version (${version} vs. ${macros_version}"
+            exit 1
+          fi
+          echo "Determined crate version: ${version}"
+          echo "version=${version}" >> $GITHUB_OUTPUT
   test:
     uses: ./.github/workflows/test.yml
     secrets: inherit
@@ -43,36 +43,36 @@ jobs:
     needs: [test, version]
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: dtolnay/rust-toolchain@stable
-    - name: Dry-run package creation
-      # Can't verify test-log for it may depend on yet-to-be-published
-      # test-log-macros.
-      run: cargo package --package macros --workspace --exclude test-log
-    - name: Create git tag
-      env:
-        version: ${{ needs.version.outputs.version }}
-      run: |
-        curl --location \
-          --fail-with-body \
-          --request POST \
-          --url https://api.github.com/repos/${{ github.repository }}/releases \
-          --header "Accept: application/vnd.github+json" \
-          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
-          --header "X-GitHub-Api-Version: 2022-11-28" \
-          --data "{
-              \"tag_name\":\"v${version}\",
-              \"target_commitish\":\"${{ github.ref }}\",
-              \"name\":\"v${version}\",
-              \"draft\":false,
-              \"prerelease\":false,
-              \"generate_release_notes\":false
-            }"
-    - name: Publish test-log-macros
-      run: cd macros/ && cargo publish --no-verify --token "${CARGO_REGISTRY_TOKEN}"
-      env:
-        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-    - name: Publish test-log
-      run: cargo publish --no-verify --token "${CARGO_REGISTRY_TOKEN}"
-      env:
-        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
+      - uses: actions/checkout@v4
+      - uses: dtolnay/rust-toolchain@stable
+      - name: Dry-run package creation
+        # Can't verify test-trace for it may depend on yet-to-be-published
+        # test-trace-macros.
+        run: cargo package --package macros --workspace --exclude test-trace
+      - name: Create git tag
+        env:
+          version: ${{ needs.version.outputs.version }}
+        run: |
+          curl --location \
+            --fail-with-body \
+            --request POST \
+            --url https://api.github.com/repos/${{ github.repository }}/releases \
+            --header "Accept: application/vnd.github+json" \
+            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
+            --header "X-GitHub-Api-Version: 2022-11-28" \
+            --data "{
+                \"tag_name\":\"v${version}\",
+                \"target_commitish\":\"${{ github.ref }}\",
+                \"name\":\"v${version}\",
+                \"draft\":false,
+                \"prerelease\":false,
+                \"generate_release_notes\":false
+              }"
+      - name: Publish test-trace-macros
+        run: cd macros/ && cargo publish --no-verify --token "${CARGO_REGISTRY_TOKEN}"
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
+      - name: Publish test-trace
+        run: cargo publish --no-verify --token "${CARGO_REGISTRY_TOKEN}"
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
